Fix ECONNRESET; Fix parameter, bri, is not modifiable
Fix (1):

    2019-06-01 19:24:58.311 <error> RequestError: Error: read ECONNRESET
        at new RequestError (/Users/simon/Dropbox/Coding/node/Projects/simplehue2mqtt/node_modules/request-promise-core/lib/errors.js:14:15)
        at Request.plumbing.callback (/Users/simon/Dropbox/Coding/node/Projects/simplehue2mqtt/node_modules/request-promise-core/lib/plumbing.js:87:29)
        at Request.RP$callback [as _callback] (/Users/simon/Dropbox/Coding/node/Projects/simplehue2mqtt/node_modules/request-promise-core/lib/plumbing.js:46:31)
        at self.callback (/Users/simon/Dropbox/Coding/node/Projects/simplehue2mqtt/node_modules/request/request.js:185:22)
        at Request.emit (events.js:196:13)
        at Request.onRequestError (/Users/simon/Dropbox/Coding/node/Projects/simplehue2mqtt/node_modules/request/request.js:881:8)
        at ClientRequest.emit (events.js:196:13)
        at Socket.socketErrorListener (_http_client.js:402:9)
        at Socket.emit (events.js:196:13)
        at emitErrorNT (internal/streams/destroy.js:91:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
        at processTicksAndRejections (internal/process/task_queues.js:84:17) {
      name: 'RequestError',
      message: 'Error: read ECONNRESET',
      cause: Error: read ECONNRESET
          at TCP.onStreamRead (internal/stream_base_commons.js:183:27) {
        errno: 'ECONNRESET',
        code: 'ECONNRESET',
        syscall: 'read'
      },
      error: Error: read ECONNRESET
          at TCP.onStreamRead (internal/stream_base_commons.js:183:27) {
        errno: 'ECONNRESET',
        code: 'ECONNRESET',
        syscall: 'read'
      },
      options: {
        uri: 'http://10.1.1.52/api/0WUuIJSl01ZXxSrc2DfK6tFyuE0FSEKCiirCzubB/lights',
        json: true,
        callback: [Function: RP$callback],
        transform: undefined,
        simple: true,
        resolveWithFullResponse: false,
        transform2xxOnly: false
      },
      response: undefined
    }

Fix (2):

    2019-06-01 19:25:06.191 <error> [
      {
        error: {
          type: 201,
          address: '/lights/1/state/bri',
          description: 'parameter, bri, is not modifiable. Device is set to off.'
        }
      },
      { success: { '/lights/1/state/on': false } }
    ]